/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/9b8dff48-8e37-4b93-b256-09b38b34d40b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String cloudLocation;
  String cloudMapsLink;
  String cloudUptime;
  float cloudAltitude;
  float cloudHumidity;
  float cloudPressure;
  float cloudTemperature;
  int cloudAncientHelmet;
  int cloudAncientStatue;
  int cloudAncientVase;
  int cloudAverageBottom;
  int cloudAverageLeft;
  int cloudAverageRight;
  int cloudAverageTop;
  int cloudCandleHolder;
  int cloudLight;
  int cloudRain;
  bool cloudAlertDetected;
  bool cloudArtifactDetected;
  bool cloudBackward;
  bool cloudCloseCurtains;
  bool cloudCloseFrontCurtains;
  bool cloudCloseLeftCurtains;
  bool cloudCloseRearCurtains;
  bool cloudCloseRightCurtains;
  bool cloudFanState;
  bool cloudForward;
  bool cloudLeft;
  bool cloudLightState;
  bool cloudManualCurtains;
  bool cloudManualDrive;
  bool cloudManualFan;
  bool cloudManualLight;
  bool cloudOpenCurtains;
  bool cloudOpenFrontCurtains;
  bool cloudOpenLeftCurtains;
  bool cloudOpenRearCurtains;
  bool cloudOpenRightCurtains;
  bool cloudRight;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

/***************************************************

* KALIPSO – FLL UNEARTHED 2025/26
* Ομάδα: Robo+art(iseis)
*
* Περιγραφή:
* Η KALIPSO είναι ένα έξυπνο αυτόνομο σύστημα που
* σχεδιάστηκε για την υποστήριξη αρχαιολόγων σε
* απαιτητικά περιβάλλοντα ανασκαφών.
*
* Συνδυάζει αισθητήρες, αυτοματισμούς και cloud
* τεχνολογία για να βελτιώσει τις συνθήκες εργασίας
* και την ασφάλεια στο πεδίο.
*
* =================================================
* ΒΑΣΙΚΕΣ ΛΕΙΤΟΥΡΓΙΕΣ
* =================================================
*
* [LIGHT TRACKING SYSTEM]
* * Παρακολουθεί την ένταση φωτός από πολλαπλούς αισθητήρες
* * Υπολογίζει την καλύτερη κατεύθυνση φωτισμού
* * Στρέφει το σύστημα προς την πηγή φωτός
*
* [MOBILITY SYSTEM]
* * Κινείται με DC motors (4WD)
* * Υποστηρίζει:
* → Μπροστά / Πίσω
* → Αριστερά / Δεξιά
* * Αυτόνομη ή χειροκίνητη κίνηση μέσω Cloud
*
* [SMART CURTAIN SYSTEM]
* * Αυτόματο άνοιγμα / κλείσιμο κουρτινών
* * Ενεργοποίηση βάσει βροχής (rain sensor)
* * Προστασία αρχαιολογικών ευρημάτων
*
* [ENVIRONMENT MONITORING]
* * Θερμοκρασία
* * Υγρασία
* * Πίεση
* * Υψόμετρο
* * Φως
* * Βροχή
*
* [AUTOMATIONS]
* * Αυτόματος φωτισμός όταν μειώνεται το φως
* * Αυτόματη ενεργοποίηση ανεμιστήρα σε υψηλή θερμοκρασία
* * Ηχητικές ειδοποιήσεις (buzzer alerts)
*
* [CLOUD CONTROL SYSTEM]
* * Χειροκίνητος έλεγχος μέσω Arduino Cloud
* * Υποστήριξη:
* → Κίνησης
* → Φωτισμού
* → Ανεμιστήρα
* → Κουρτινών (global & individual)
*
* [DISPLAY SYSTEM]
* * LCD 20x4
* * Εμφάνιση περιβαλλοντικών δεδομένων
* * Εμφάνιση καταστάσεων συστήματος
* * UI Manager για αποφυγή conflicts
*
* [SIMULATION SYSTEM]
* * Fake sensor data (base + offset)
* * Δυνατότητα demo χωρίς πραγματικούς αισθητήρες
* * Εύκολη αλλαγή σεναρίων (π.χ. ήλιος, βροχή)
*
* =================================================
* ΣΤΟΧΟΣ PROJECT
* =================================================
*
* Η KALIPSO στοχεύει στη δημιουργία ενός
* ευφυούς περιβάλλοντος εργασίας για αρχαιολόγους,
* συνδυάζοντας τεχνολογία και αυτοματοποίηση
* για μεγαλύτερη αποδοτικότητα και ασφάλεια.
*

***************************************************/


// =================================================
// INCLUDE ΒΙΒΛΙΟΘΗΚΩΝ & ΑΡΧΙΚΟΠΟΙΗΣΗ ΣΥΣΤΗΜΑΤΟΣ
// =================================================
// Περιλαμβάνει:
// - Arduino Cloud properties
// - Βιβλιοθήκες αισθητήρων
// - LCD
// - HuskyLens
// - Simulation
// =================================================
#include "thingProperties.h"
#include <LiquidCrystal_I2C.h>
#include <DFRobot_DHT20.h>
#include <DFRobot_ICP10111.h>
#include <DFRobot_HuskylensV2.h>
#include "simulation.h"


// =================================================
// ΑΝΤΙΚΕΙΜΕΝΑ ΣΥΣΚΕΥΩΝ
// =================================================

// LCD 20x4 (διεύθυνση 0x27)
LiquidCrystal_I2C lcd(0x27, 20, 4);

// Αισθητήρας θερμοκρασίας & υγρασίας
DFRobot_DHT20 dht20(&Wire1);

// Αισθητήρας πίεσης & υψομέτρου
DFRobot_ICP10111 icp(&Wire1);

// AI κάμερα HuskyLens
HuskylensV2 huskylens;


// =================================================
// SYSTEM TIMING CONSTANTS
// =================================================
// Χρόνοι καθυστέρησης για αρχικοποίηση συστήματος
// =================================================

// -------- CONSTANTS --------
const int serialStartupDelay = 1500;
const int i2cStartupDelay = 100;
const int sensorRetryDelay = 1000;

String uptime;

// =================================================
// CLOUD SYSTEM
// =================================================
// Διαχείριση σύνδεσης και retry logic
// =================================================

// -------- CONSTANTS --------
const int switchCloudPin = 5;
const int maxFailedAttempts = 5;

// -------- VARIABLES --------
int failedAttempts = 0;

// -------- STATE --------
enum CloudState {
  CLOUD_CONNECTING,
  CLOUD_ONLINE,
  CLOUD_OFFLINE,
  CLOUD_MANUAL_OFFLINE
};

CloudState cloudState;

// =================================================
// CLOUD TIMEOUT SETTINGS
// =================================================

// Χρόνος αναμονής για αρχική σύνδεση Cloud (ms)
const int cloudConnectionTimeout = 10000;

// Επιπλέον χρόνος για να θεωρηθεί αποτυχημένο το reconnect
const int cloudReconnectGracePeriod = 2000;

// =================================================
// CLOUD STATUS LEDS
// =================================================

// -------- CONSTANTS --------
const int cloudLedGreenPin = 38;
const int cloudLedRedPin = 39;


// =================================================
// BLINK SETTINGS (LED STATUS)
// =================================================

// Συνολικός χρόνος κύκλου blink (ms)
const int blinkInterval = 500;

// Duty cycle (πόσο χρόνο είναι ON μέσα στον κύκλο)
const int blinkOnTime = 250;


// =================================================
// SERVO ΚΙΝΗΤΗΡΕΣ
// =================================================
// Έλεγχος κατεύθυνσης φωτός (tracking)
// =================================================

// -------- CONSTANTS --------
const int servoHoriPin = 10;
const int servoVertPin = 11;

const int servoHoriLimitHigh = 170;
const int servoHoriLimitLow = 10;

const int servoVertLimitHigh = 105;
const int servoVertLimitLow = 75;

const int servoPeriodDelay = 20000;

const int servoTestStepDelay = 20;
const int servoTestDirectionDelay = 500;
const int servoTestResetDelay = 1000;

// Ανοχή για αποφυγή "τρέμουλου"
const int tol = 90;

// -------- VARIABLES --------
int servoHoriPos = 90;
int servoVertPos = 90;


// =================================================
// LIGHT SYSTEM (ΑΙΣΘΗΤΗΡΕΣ ΦΩΤΟΣ)
// =================================================
// LDR sensors + υπολογισμοί φωτός
// =================================================

// -------- CONSTANTS --------
const int ldrltPin = A0;
const int ldrldPin = A1;
const int ldrrtPin = A2;
const int ldrrdPin = A3;

const int switchLightPin = 3;

// -------- VARIABLES --------
int lt, rt, ld, rd;

int avt, avd;
int avl, avr;

int avgLight;
int light;

int avtPerc, avdPerc;
int avrPerc, avlPerc;

int dvert, dhoriz;

// -------- FLAGS --------
bool lightTrackingEnabled = true;
bool lastSwitchState = HIGH;


// =================================================
// RAIN SYSTEM (ΑΙΣΘΗΤΗΡΑΣ ΒΡΟΧΗΣ)
// =================================================

// -------- CONSTANTS --------
const int rainDropPin = A4;
const int rainHighThreshold = 75;
const int rainLowThreshold = 40;

// -------- VARIABLES --------
int rain;

// -------- FLAGS --------
bool rainState = false;


// =================================================
// DHT SENSOR (ΑΙΣΘΗΤΗΡΑΣ ΘΕΡΜΟΚΡΑΣΙΑΣ - ΥΓΡΑΣΙΑΣ)
// =================================================
// Τιμές θερμοκρασίας και υγρασίας
float temperature;
float humidity;

// =================================================
// SEN SENSOR (ΑΙΣΘΗΤΗΡΑΣ ΒΑΡΟΜΕΤΡΙΚΗΣ ΠΙΕΣΗΣ - ΥΨΟΜΕΡΤΟΥ)
// =================================================
// Τιμές πίεσης και υψομέτρου
float pressure;
float altitude;

// =================================================
// GNSS SENSOR (GPS - ΘΕΣΗ)
// =================================================
// Τρέχουσες τιμές γεωγραφικής θέσης
float latitude;
float longitude;

// Κατάσταση GPS σήματος
bool gnssFix;

// =================================================
// DC MOTORS SYSTEM
// =================================================
// Κίνηση συστήματος & κουρτίνες
// =================================================

// -------- CONSTANTS --------

// Κάθετη κίνηση
const int ena_1 = 12;
const int enb_1 = 13;

const int motor1pin1 = 22; 
const int motor1pin2 = 24;
const int motor2pin1 = 23;
const int motor2pin2 = 25;

// Οριζόντια κίνηση
const int ena_2 = 8;
const int enb_2 = 9;

const int motor3pin1 = 26;
const int motor3pin2 = 28;
const int motor4pin1 = 27; 
const int motor4pin2 = 29;

// Κατευθύνσεις κίνησης ρομπότ
// Χρησιμοποιείται αντί για "μαγικούς αριθμούς"
enum MovementDirection {
  DIR_STOP,
  DIR_FORWARD,
  DIR_BACKWARD,
  DIR_RIGHT,
  DIR_LEFT
};

// Κουρτίνες
const int frontCurtainPin1 = 50;
const int frontCurtainPin2 = 51;

const int rearCurtainPin1 = 44;
const int rearCurtainPin2 = 45;

const int rightCurtainPin1 = 52;
const int rightCurtainPin2 = 53;

const int leftCurtainPin1 = 46;
const int leftCurtainPin2 = 47;


// =================================================
// LIGHT SYSTEM (ΦΩΤΙΣΜΟΣ)
// =================================================
// LIGHT για χαμηλό φωτισμό (hysteresis)
// =================================================

// -------- CONSTANTS --------
const int lightPin = 40;
const int lightLowThreshold = 10;
const int lightHighThreshold = 25;

// -------- FLAGS --------
bool lightState = false;


// =================================================
// FAN SYSTEM (ΑΝΕΜΙΣΤΗΡΑΣ)
// =================================================
// FAN για υψηλή θερμοκρασία (hysteresis)
// =================================================

// -------- CONSTANTS --------
const int fanPin = 41;
const int fanLowThreshold = 27;
const int fanHighThreshold = 30;

// -------- FLAGS --------
bool fanState = false;


// =================================================
// BUZZER SYSTEM (ΗΧΗΤΙΚΟ ALERT)
// =================================================
// Διαχειρίζεται το buzzer για ειδοποιήσεις.
// =================================================

// -------- PIN --------
// Pin σύνδεσης buzzer (PWM capable για tone)
const int buzzerPin = 4;

// -------- STATES --------
// Τρέχουσα κατάσταση buzzer:
bool buzzerState = false;

// -------- CONDITION --------
// Συνθήκη ενεργοποίησης alert:
bool alertCondition = false;
bool alertDetected = false;
bool lastAlertState = false;


// =================================================
// AI SYSTEM (HUSKYLENS)
// =================================================
// Μετρητές αντικειμένων & έλεγχος display
// =================================================

// -------- VARIABLES --------
int objectCounters[5] = {0, 0, 0, 0, 0};
int lastDetectedID = 0;

// -------- FLAGS --------
bool aiDisplayActive = false;
bool artifactDetected = false;


// =================================================
// DISPLAY SYSTEM
// =================================================

// -------- FLAGS --------
bool modeMessageActive = false;


// =================================================
// TIMERS (millis)
// =================================================
// Όλοι οι χρόνοι συστήματος (non-blocking)
// =================================================

// -------- VARIABLES --------
unsigned long myTime;
unsigned long cloudTime;
unsigned long lightReadTime;
unsigned long sensorsReadTime;
unsigned long displaySensorsTime;
unsigned long displayLightSensorsTime;
unsigned long readLightAVGTime;
unsigned long readFanTime;
unsigned long readMovingTime;
unsigned long readRainTime;
unsigned long readhuskylensTime;
unsigned long aiDisplayStartTime;
unsigned long modeMessageStartTime;
unsigned long cloudVariablesTime;
unsigned long curtainTime;
unsigned long motionStartTime;
unsigned long buzzerTimer;

unsigned long lastAttemptTime;
unsigned long lastCloudUpdateTime;

// -------- CONSTANTS --------
const int cloudInterval = 10;
const int lightReadInterval = 50;
const int sensorsReadInterval = 2000;
const int displaySensorsInterval = 3000;
const int displayLightSensorsInterval = 500;
const int readLightAVGInterval = 1000;
const int readFanInterval = 1000;
const int readMovingInterval = 3000;
const int readRainInterval = 2500;
const int readhuskylensInterval = 3000;
const int aiDisplayStartInterval = 1500;
const int modeMessageStartInterval = 2000;
const int cloudVariablesInterval = 3000;

const int fastUpdateInterval = 100;
const int slowUpdateInterval = 5000;
const int buzzerInterval = 300;

const int curtainDelay = 6000;
const int motionDelay = 250;

// =================================================
// SIMULATION SYSTEM
// =================================================
// Χρησιμοποιείται όταν αισθητήρες δεν λειτουργούν
// =================================================

// -------- FLAGS --------
bool useFakeDataLight = false;
bool useFakeDataRain = false;
bool useFakeDataDHT = false;
bool useFakeDataSEN = false;
bool useFakeDataHL = false;
bool useFakeDataGNSS = false;

// -------- FLAGS --------
bool offlineMode = false;


// =================================================
// DEBUG MODE
// =================================================
// Ενεργοποιεί Serial prints για debugging
// =================================================

// -------- FLAGS --------
bool debugMode = true;


// =================================================
// SETUP – ΑΡΧΙΚΟΠΟΙΗΣΗ ΣΥΣΤΗΜΑΤΟΣ
// =================================================
// Αρχικοποιεί όλο το σύστημα:
//
// - Serial επικοινωνία
// - Pins (αισθητήρες / servo / LED)
// - I2C συσκευές
// - LCD
// - Sensors (DHT, SEN, HuskyLens, GNSS)
// - Cloud
//
// Εκτελείται ΜΟΝΟ μία φορά στην εκκίνηση
// =================================================
void setup() {

  // Εκκίνηση Serial επικοινωνίας (debug)
  Serial.begin(115200);
  delay(serialStartupDelay);

  // Εκκίνηση Serial2 (HuskyLens)
  Serial2.begin(9600);
  delay(serialStartupDelay);
  
  // Σύνδεση servo στα pins
  pinMode(servoHoriPin, OUTPUT);
  pinMode(servoVertPin, OUTPUT);

  // Θέση εκκίνησης servo
  controlServoPWM(servoHoriPin, servoHoriPos);
  controlServoPWM(servoVertPin, servoVertPos);

  // Ορισμός pin ως έξοδοι
  pinMode(ena_1, OUTPUT);
  pinMode(enb_1, OUTPUT);

  pinMode(motor1pin1, OUTPUT);
  pinMode(motor1pin2, OUTPUT);

  pinMode(motor2pin1, OUTPUT);
  pinMode(motor2pin2, OUTPUT);

  pinMode(ena_2, OUTPUT);
  pinMode(enb_2, OUTPUT);

  pinMode(motor3pin1, OUTPUT);
  pinMode(motor3pin2, OUTPUT);

  pinMode(motor4pin1, OUTPUT);
  pinMode(motor4pin2, OUTPUT);

  pinMode(frontCurtainPin1, OUTPUT);
  pinMode(frontCurtainPin2, OUTPUT);

  pinMode(rearCurtainPin1, OUTPUT);
  pinMode(rearCurtainPin2, OUTPUT);

  pinMode(leftCurtainPin1, OUTPUT);
  pinMode(leftCurtainPin2, OUTPUT);

  pinMode(rightCurtainPin1, OUTPUT);
  pinMode(rightCurtainPin2, OUTPUT);

  pinMode(cloudLedGreenPin, OUTPUT);
  pinMode(cloudLedRedPin, OUTPUT);
  digitalWrite(cloudLedGreenPin, HIGH);
  digitalWrite(cloudLedRedPin, HIGH);

  pinMode(lightPin, OUTPUT);
  digitalWrite(lightPin, LOW);

  pinMode(fanPin, OUTPUT);
  digitalWrite(fanPin, LOW);

  pinMode(buzzerPin, OUTPUT);
  digitalWrite(buzzerPin, LOW);

  // Ορισμός pin ως είσοδος
  // Τέσσερις LDR γύρω από τον αισθητήρα
  pinMode(ldrltPin, INPUT);
  pinMode(ldrrtPin, INPUT);
  pinMode(ldrldPin, INPUT);
  pinMode(ldrrdPin, INPUT);

  // Αισθητήρας βροχής
  pinMode(rainDropPin, INPUT);

  // Διακόπτης
  pinMode(switchLightPin, INPUT_PULLUP);
  pinMode(switchCloudPin, INPUT_PULLUP);

  // Δίνει διαφορετικά νούμερα κάθε φορά 
  randomSeed(analogRead(A5));  // ← εδώ

  // ===== I2C =====
  Wire.begin();
  delay(i2cStartupDelay);

  Wire1.begin();
  delay(i2cStartupDelay);

  // ===== LCD =====
  lcd.init();
  lcd.backlight();

  // Intro οθόνη
  displayIntro();

  // Test servo κίνησης
  testServoSweep();
  
  // Καθαρισμός οθόνης
  lcd.clear();

  displayLineCentered(0, "*INITIALISE*");

  // ===== DHT20 =====
  if (!useFakeDataDHT) {

    int retries = 0;

    // Προσπάθεια εκκίνησης αισθητήρα
    while (dht20.begin()) {  
      Serial.print("DHT20 failed - ");
      Serial.println(retries + 1);

      delay(sensorRetryDelay);
      retries++;
      
      // fallback σε fake mode
      if (retries >= maxFailedAttempts) {
        useFakeDataDHT = true;
        break;
      }
    }
    
    if (!useFakeDataDHT) {
      Serial.println("DHT20 connected successfully");
      displayLineCentered(1, "DHT20 connected");
    } else {
      Serial.println("Switching to FAKE DHT mode");
      displayLineCentered(1, "DHT20 failed");
    }

    delay(modeMessageStartInterval / 2);

  } else {
    Serial.println("Switching to FAKE DHT mode");
    displayLineCentered(1, "DHT20 FAKE mode");
    delay(modeMessageStartInterval / 2);
  }

  // ===== SEN0516 =====
  if (!useFakeDataSEN) {

    int retries = 0;

    // Προσπάθεια εκκίνησης αισθητήρα
    while (icp.begin()) {

      Serial.print("SEN0516 failed - ");
      Serial.println(retries + 1);

      delay(sensorRetryDelay);
      retries++;

      // fallback σε fake mode
      if (retries >= maxFailedAttempts) {
        useFakeDataSEN = true;
        break;
      }
    }
    
    if (!useFakeDataSEN) {

      icp.setWorkPattern(icp.eNormal);

      Serial.println("SEN0516 connected successfully");
      displayLineCentered(2, "SEN0516 connected");

    } else {

      Serial.println("Switching to FAKE SEN mode");
      displayLineCentered(2, "SEN0516 failed");
    }

    delay(modeMessageStartInterval / 2);

  } else {

    Serial.println("Switching to FAKE SEN mode");
    displayLineCentered(2, "SEN0516 FAKE mode");
    delay(modeMessageStartInterval / 2);
  }

  // ===== HUSKYLENS =====
  if (!useFakeDataHL) {

    int retries = 0;
      
    // Προσπάθεια εκκίνησης κάμερας
    while (!huskylens.begin(Serial2)){

      Serial.print("HuskyLens failed - ");
      Serial.println(retries + 1);

      delay(sensorRetryDelay / 3);
      retries++;

      // fallback σε fake mode
      if (retries >= maxFailedAttempts) {
        useFakeDataHL = true;
        break;
      }
    }
    
    if (!useFakeDataHL) {

      Serial.println("HuskyLens connected successfully");
      displayLineCentered(3, "HuskyLens connected");

    } else {

      Serial.println("Switching to FAKE HuskyLens mode");
      displayLineCentered(3, "HuskyLens failed");
    }

    delay(modeMessageStartInterval / 2);

  } else {

    Serial.println("Switching to FAKE HuskyLens mode");
    displayLineCentered(3, "HuskyLens FAKE mode");
    delay(modeMessageStartInterval / 2);
  }

  // ===== CLOUD =====
  
  // Έλεγχος διακόπτη ενεργοποίησης cloud
  readCloudSwitch();
  delay(modeMessageStartInterval);

  // Αν επιτρέπεται η χρήση Cloud
  if(!offlineMode) {
    // Αρχικοποίηση cloud μεταβλητών
    initProperties();

    // Αρχικοποίηση cloud
    initCloud();
  }
  
  // Update LED με βάση κατάσταση
  updateCloudStatusLEDs();
  
  // Τελικός καθαρισμός LCD
  lcd.clear();

  // Έλεγχος διακόπτη ενεργοποίησης tracking
  lastSwitchState = !digitalRead(switchLightPin);
  readTrackingSwitch();
  
  delay(modeMessageStartInterval);
}

// =================================================
// MAIN LOOP
// =================================================
// Κεντρικός βρόχος προγράμματος (τρέχει συνεχώς)
//
// Περιλαμβάνει:
// - Χρονισμό (millis)
// - Cloud διαχείριση
// - Light tracking & κίνηση
// - Sensors (φως / βροχή)
// - LCD display
// - HuskyLens
// - Cloud commands
// =================================================
void loop() {

  // Τρέχων χρόνος (βάση για όλα τα timers)
  myTime = millis();

  // Μετατροπή uptime σε μορφή HH:mm:ss
  uptime = formatTime(myTime);
  
  
  // =================================================
  // CLOUD SYSTEM
  // =================================================

  // Αν επιτρέπεται η χρήση Cloud
  if(!offlineMode) {
    // Ενημερώνει την μεταβλητη Cloud
    cloudUptime = uptime;
  
    // Διαχείριση σύνδεσης Cloud (connect / reconnect / offline)
    updateCloudConnection();
  }
    
  // Ενημέρωση LED κατάστασης Cloud
  updateCloudStatusLEDs();
  

  // =================================================
  // LIGHT TRACKING SYSTEM
  // =================================================

  // Παρακολούθηση φωτός (υπολογισμοί LDR)
  trackLightSensors();

  // Κίνηση servo οριζόντια
  // controlServoPWM(servoHoriPin, servoHoriPos);
  
  // Κίνηση servo κάθετα
  // controlServoPWM(servoVertPin, servoVertPos);

  // Έλεγχος διακόπτη ενεργοποίησης tracking
  readTrackingSwitch();

  // Κίνηση μοτέρ βάσει φωτός (αν είναι ενεργό)
  if (lightTrackingEnabled) {
    controlMotorsByLight();
  }
  

  // =================================================
  // ENVIRONMENT SYSTEM
  // =================================================
  
  // Συλλογή τιμών απο αισθητήρες
  readAllSensors();
  
  // Έλεγχος βοηθητικού φωτισμού (LIGHT)
  controlLight();

  // Έλεγχος βοηθητικού ανεμιστήρα (FAN)
  controlFan();

  // Έλεγχος βροχής
  controlRain();

  // Έλεγχος ειδοποιήσεων
  controlBuzzer();

  // =================================================
  // DISPLAY SYSTEM
  // =================================================

  // Εμφάνιση τιμών φωτός στην LCD
  displayLightData();
  
  // Εμφάνιση περιβαλλοντικών δεδομένων
  displayEnvironmentData();

  // Διαχείριση προσωρινών μηνυμάτων LCD
  updateDisplayMessages();


  // =================================================
  // AI SYSTEM (HUSKYLENS)
  // =================================================

  // Επεξεργασία δεδομένων από HuskyLens
  updateHuskyLens();


  // =================================================
  // CLOUD DATA & COMMANDS
  // =================================================

  // Αν επιτρέπεται η χρήση Cloud
  if(!offlineMode) {
    // Ενημέρωση τιμών στο Arduino Cloud
    updateCloudData();
    
    // Έλεγχος φωτισμού μέσω Cloud
    controlCloudLight();

    // Έλεγχος ανεμιστήρα μέσω Cloud
    controlCloudFan();
  
    // Έλεγχος κίνησης μέσω Cloud
    controlCloudMovement();
  
    // Έλεγχος κουρτινών μέσω Cloud
    controlCloudCurtains();
  }
}


/*
  Since CloudForward is READ_WRITE variable, onCloudForwardChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudForwardChange()  {
  // Add your code here to act upon CloudForward change
}

/*
  Since CloudBackward is READ_WRITE variable, onCloudBackwardChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudBackwardChange()  {
  // Add your code here to act upon CloudBackward change
}

/*
  Since CloudLeft is READ_WRITE variable, onCloudLeftChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudLeftChange()  {
  // Add your code here to act upon CloudLeft change
}

/*
  Since CloudRight is READ_WRITE variable, onCloudRightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudRightChange()  {
  // Add your code here to act upon CloudRight change
}

/*
  Since CloudUpCurtains is READ_WRITE variable, onCloudUpCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudUpCurtainsChange()  {
  // Add your code here to act upon CloudUpCurtains change
}

/*
  Since CloudOpenCurtains is READ_WRITE variable, onCloudOpenCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudOpenCurtainsChange()  {
  // Add your code here to act upon CloudOpenCurtains change
}

/*
  Since CloudCloseCurtains is READ_WRITE variable, onCloudCloseCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudCloseCurtainsChange()  {
  // Add your code here to act upon CloudCloseCurtains change
}

/*
  Since CloudOpenFrontCurtains is READ_WRITE variable, onCloudOpenFrontCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudOpenFrontCurtainsChange()  {
  // Add your code here to act upon CloudOpenFrontCurtains change
}

/*
  Since CloudCloseFrontCurtains is READ_WRITE variable, onCloudCloseFrontCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudCloseFrontCurtainsChange()  {
  // Add your code here to act upon CloudCloseFrontCurtains change
}

/*
  Since CloudOpenRearCurtains is READ_WRITE variable, onCloudOpenRearCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudOpenRearCurtainsChange()  {
  // Add your code here to act upon CloudOpenRearCurtains change
}

/*
  Since CloudCloseRearCurtains is READ_WRITE variable, onCloudCloseRearCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudCloseRearCurtainsChange()  {
  // Add your code here to act upon CloudCloseRearCurtains change
}

/*
  Since CloudOpenRightCurtains is READ_WRITE variable, onCloudOpenRightCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudOpenRightCurtainsChange()  {
  // Add your code here to act upon CloudOpenRightCurtains change
}

/*
  Since CloudCloseRightCurtains is READ_WRITE variable, onCloudCloseRightCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudCloseRightCurtainsChange()  {
  // Add your code here to act upon CloudCloseRightCurtains change
}

/*
  Since CloudOpenLeftCurtains is READ_WRITE variable, onCloudOpenLeftCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudOpenLeftCurtainsChange()  {
  // Add your code here to act upon CloudOpenLeftCurtains change
}

/*
  Since CloudCloseLeftCurtains is READ_WRITE variable, onCloudCloseLeftCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudCloseLeftCurtainsChange()  {
  // Add your code here to act upon CloudCloseLeftCurtains change
}

/*
  Since CloudManualLight is READ_WRITE variable, onCloudManualLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudManualLightChange()  {
  // Add your code here to act upon CloudManualLight change
}

/*
  Since CloudLightState is READ_WRITE variable, onCloudLightStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudLightStateChange()  {
  // Add your code here to act upon CloudLightState change
}


/*
  Since CloudFanState is READ_WRITE variable, onCloudFanStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudFanStateChange()  {
  // Add your code here to act upon CloudFanState change
}

/*
  Since CloudManualFan is READ_WRITE variable, onCloudManualFanChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudManualFanChange()  {
  // Add your code here to act upon CloudManualFan change
}



/*
  Since CloudManualDrive is READ_WRITE variable, onCloudManualDriveChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudManualDriveChange()  {
  // Add your code here to act upon CloudManualDrive change
}

/*
  Since CloudManualCurtains is READ_WRITE variable, onCloudManualCurtainsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudManualCurtainsChange()  {
  // Add your code here to act upon CloudManualCurtains change
}